[package]
name = "Wombat"
version = "0.1.0"
authors = ["Frédéric Cabestre <frederic.cabestre@free.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
